/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status__1 = IDL.Variant({
  'review' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rating = IDL.Record({
  'communication' : IDL.Nat,
  'reliability' : IDL.Nat,
  'professionalism' : IDL.Nat,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'status' : Status__1,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'city' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'ratings' : Rating,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'priceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'category' : IDL.Text,
});
export const Model = IDL.Variant({
  'leadFee' : IDL.Null,
  'none' : IDL.Null,
  'featuredPlacement' : IDL.Null,
  'commission' : IDL.Null,
  'listingFee' : IDL.Null,
});
export const Config = IDL.Record({
  'leadFee' : IDL.Opt(IDL.Int),
  'model' : Model,
  'featuredPlacementFee' : IDL.Opt(IDL.Int),
  'commissionRate' : IDL.Opt(IDL.Int),
  'listingFee' : IDL.Opt(IDL.Int),
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const Request = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'scheduledTime' : IDL.Opt(Time),
  'companionId' : IDL.Text,
  'notes' : IDL.Text,
  'requestTime' : Time,
  'requesterId' : IDL.Principal,
});
export const CommissionDue = IDL.Record({
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'bookingId' : IDL.Text,
  'amount' : IDL.Int,
  'requesterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const Type = IDL.Variant({
  'offer' : IDL.Null,
  'message' : IDL.Null,
  'bookingRequest' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'messageType' : Type,
  'timestamp' : Time,
  'bookingRequestId' : IDL.Opt(IDL.Text),
  'receiver' : IDL.Principal,
});
export const MessageThreadInfo = IDL.Record({
  'requester' : IDL.Principal,
  'companionId' : IDL.Text,
  'companionPrincipal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminRevertBan' : IDL.Func([IDL.Principal], [], []),
  'adminUpdateProfileStatus' : IDL.Func([IDL.Text, Status__1], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'canUserAccessMessages' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'confirmCommissionPayment' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'createOrUpdateCallerCompanionProfile' : IDL.Func(
      [Profile, IDL.Bool],
      [],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'getActiveMonetizationConfig' : IDL.Func([], [Config], ['query']),
  'getActiveProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerCommissionDues' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(CommissionDue))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessagesByParticipants' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMessagesByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getPlatformEarnings' : IDL.Func([], [IDL.Int], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Request)], ['query']),
  'getUserMessageThreads' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MessageThreadInfo)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerBanned' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([Message], [], []),
  'submitBookingRequest' : IDL.Func([Request], [], []),
  'updateBookingRequestStatus' : IDL.Func([IDL.Text, Status], [], []),
  'updateMonetizationConfig' : IDL.Func([Config], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status__1 = IDL.Variant({
    'review' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rating = IDL.Record({
    'communication' : IDL.Nat,
    'reliability' : IDL.Nat,
    'professionalism' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'status' : Status__1,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'city' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'ratings' : Rating,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'priceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'category' : IDL.Text,
  });
  const Model = IDL.Variant({
    'leadFee' : IDL.Null,
    'none' : IDL.Null,
    'featuredPlacement' : IDL.Null,
    'commission' : IDL.Null,
    'listingFee' : IDL.Null,
  });
  const Config = IDL.Record({
    'leadFee' : IDL.Opt(IDL.Int),
    'model' : Model,
    'featuredPlacementFee' : IDL.Opt(IDL.Int),
    'commissionRate' : IDL.Opt(IDL.Int),
    'listingFee' : IDL.Opt(IDL.Int),
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const Request = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'scheduledTime' : IDL.Opt(Time),
    'companionId' : IDL.Text,
    'notes' : IDL.Text,
    'requestTime' : Time,
    'requesterId' : IDL.Principal,
  });
  const CommissionDue = IDL.Record({
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'bookingId' : IDL.Text,
    'amount' : IDL.Int,
    'requesterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const Type = IDL.Variant({
    'offer' : IDL.Null,
    'message' : IDL.Null,
    'bookingRequest' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'messageType' : Type,
    'timestamp' : Time,
    'bookingRequestId' : IDL.Opt(IDL.Text),
    'receiver' : IDL.Principal,
  });
  const MessageThreadInfo = IDL.Record({
    'requester' : IDL.Principal,
    'companionId' : IDL.Text,
    'companionPrincipal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminRevertBan' : IDL.Func([IDL.Principal], [], []),
    'adminUpdateProfileStatus' : IDL.Func([IDL.Text, Status__1], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'canUserAccessMessages' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'confirmCommissionPayment' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'createOrUpdateCallerCompanionProfile' : IDL.Func(
        [Profile, IDL.Bool],
        [],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'getActiveMonetizationConfig' : IDL.Func([], [Config], ['query']),
    'getActiveProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerCommissionDues' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(CommissionDue))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessagesByParticipants' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMessagesByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getPlatformEarnings' : IDL.Func([], [IDL.Int], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getUserMessageThreads' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MessageThreadInfo)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isBanned' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerBanned' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([Message], [], []),
    'submitBookingRequest' : IDL.Func([Request], [], []),
    'updateBookingRequestStatus' : IDL.Func([IDL.Text, Status], [], []),
    'updateMonetizationConfig' : IDL.Func([Config], [], []),
  });
};

export const init = ({ IDL }) => { return []; };