/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status__1 = IDL.Variant({
  'review' : IDL.Null,
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rating = IDL.Record({
  'communication' : IDL.Nat,
  'reliability' : IDL.Nat,
  'professionalism' : IDL.Nat,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'status' : Status__1,
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'languages' : IDL.Vec(IDL.Text),
  'ratings' : Rating,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'priceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'category' : IDL.Text,
});
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Time = IDL.Int;
export const Request = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'scheduledTime' : IDL.Opt(Time),
  'companionId' : IDL.Text,
  'notes' : IDL.Text,
  'requestTime' : Time,
  'requesterId' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminUpdateProfileStatus' : IDL.Func([IDL.Text, Status__1], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([Profile], [], []),
  'getActiveProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Request)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitBookingRequest' : IDL.Func([Request], [], []),
  'updateBookingRequestStatus' : IDL.Func([IDL.Text, Status], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status__1 = IDL.Variant({
    'review' : IDL.Null,
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rating = IDL.Record({
    'communication' : IDL.Nat,
    'reliability' : IDL.Nat,
    'professionalism' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'status' : Status__1,
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'languages' : IDL.Vec(IDL.Text),
    'ratings' : Rating,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'priceRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'category' : IDL.Text,
  });
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Time = IDL.Int;
  const Request = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'scheduledTime' : IDL.Opt(Time),
    'companionId' : IDL.Text,
    'notes' : IDL.Text,
    'requestTime' : Time,
    'requesterId' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminUpdateProfileStatus' : IDL.Func([IDL.Text, Status__1], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([Profile], [], []),
    'getActiveProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Request)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitBookingRequest' : IDL.Func([Request], [], []),
    'updateBookingRequestStatus' : IDL.Func([IDL.Text, Status], [], []),
  });
};

export const init = ({ IDL }) => { return []; };