/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Profile {
  'id' : string,
  'status' : Status__1,
  'principal' : Principal,
  'displayName' : string,
  'languages' : Array<string>,
  'ratings' : Rating,
  'description' : string,
  'photoUrl' : string,
  'priceRange' : { 'max' : bigint, 'min' : bigint },
  'category' : string,
}
export interface Rating {
  'communication' : bigint,
  'reliability' : bigint,
  'professionalism' : bigint,
}
export interface Request {
  'id' : string,
  'status' : Status,
  'scheduledTime' : [] | [Time],
  'companionId' : string,
  'notes' : string,
  'requestTime' : Time,
  'requesterId' : Principal,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Status__1 = { 'review' : null } |
  { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUpdateProfileStatus' : ActorMethod<[string, Status__1], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'getActiveProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllBookings' : ActorMethod<[], Array<Request>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserBookings' : ActorMethod<[Principal], Array<Request>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBookingRequest' : ActorMethod<[Request], undefined>,
  'updateBookingRequestStatus' : ActorMethod<[string, Status], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];