/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommissionDue {
  'status' : { 'pending' : null } |
    { 'paid' : null },
  'bookingId' : string,
  'amount' : bigint,
  'requesterId' : Principal,
}
export interface Config {
  'leadFee' : [] | [bigint],
  'model' : Model,
  'featuredPlacementFee' : [] | [bigint],
  'commissionRate' : [] | [bigint],
  'listingFee' : [] | [bigint],
}
export interface Message {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'content' : string,
  'sender' : Principal,
  'messageType' : Type,
  'timestamp' : Time,
  'bookingRequestId' : [] | [string],
  'receiver' : Principal,
}
export interface MessageThreadInfo {
  'requester' : Principal,
  'companionId' : string,
  'companionPrincipal' : Principal,
}
export type Model = { 'leadFee' : null } |
  { 'none' : null } |
  { 'featuredPlacement' : null } |
  { 'commission' : null } |
  { 'listingFee' : null };
export interface Profile {
  'id' : string,
  'status' : Status__1,
  'principal' : Principal,
  'displayName' : string,
  'city' : string,
  'languages' : Array<string>,
  'ratings' : Rating,
  'description' : string,
  'photoUrl' : string,
  'priceRange' : { 'max' : bigint, 'min' : bigint },
  'category' : string,
}
export interface Rating {
  'communication' : bigint,
  'reliability' : bigint,
  'professionalism' : bigint,
}
export interface Request {
  'id' : string,
  'status' : Status,
  'scheduledTime' : [] | [Time],
  'companionId' : string,
  'notes' : string,
  'requestTime' : Time,
  'requesterId' : Principal,
}
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Status__1 = { 'review' : null } |
  { 'active' : null } |
  { 'inactive' : null };
export type Time = bigint;
export type Type = { 'offer' : null } |
  { 'message' : null } |
  { 'bookingRequest' : null };
export interface UserProfile {
  'name' : string,
  'email' : [] | [string],
  'phoneNumber' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminRevertBan' : ActorMethod<[Principal], undefined>,
  'adminUpdateProfileStatus' : ActorMethod<[string, Status__1], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'canUserAccessMessages' : ActorMethod<[Principal, Principal], boolean>,
  'confirmCommissionPayment' : ActorMethod<[string, boolean], undefined>,
  'createOrUpdateCallerCompanionProfile' : ActorMethod<
    [Profile, boolean],
    undefined
  >,
  'createOrUpdateProfile' : ActorMethod<[Profile], undefined>,
  'getActiveMonetizationConfig' : ActorMethod<[], Config>,
  'getActiveProfiles' : ActorMethod<[], Array<Profile>>,
  'getAllBookings' : ActorMethod<[], Array<Request>>,
  'getAllProfiles' : ActorMethod<[], Array<Profile>>,
  'getCallerCommissionDues' : ActorMethod<[], [] | [Array<CommissionDue>]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesByParticipants' : ActorMethod<
    [Principal, Principal],
    Array<Message>
  >,
  'getMessagesByUserId' : ActorMethod<[Principal], Array<Message>>,
  'getPlatformEarnings' : ActorMethod<[], bigint>,
  'getUserBookings' : ActorMethod<[Principal], Array<Request>>,
  'getUserMessageThreads' : ActorMethod<[Principal], Array<MessageThreadInfo>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isBanned' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerBanned' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Message], undefined>,
  'submitBookingRequest' : ActorMethod<[Request], undefined>,
  'updateBookingRequestStatus' : ActorMethod<[string, Status], undefined>,
  'updateMonetizationConfig' : ActorMethod<[Config], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];