/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MessageThreadInfo {
    requester: Principal;
    companionId: string;
    companionPrincipal: Principal;
}
export type Time = bigint;
export interface Rating {
    communication: bigint;
    reliability: bigint;
    professionalism: bigint;
}
export interface Config {
    leadFee?: bigint;
    model: Model;
    featuredPlacementFee?: bigint;
    commissionRate?: bigint;
    listingFee?: bigint;
}
export interface Profile {
    id: string;
    status: Status__1;
    principal: Principal;
    displayName: string;
    city: string;
    languages: Array<string>;
    ratings: Rating;
    description: string;
    photoUrl: string;
    priceRange: {
        max: bigint;
        min: bigint;
    };
    category: string;
}
export interface Request {
    id: string;
    status: Status;
    scheduledTime?: Time;
    companionId: string;
    notes: string;
    requestTime: Time;
    requesterId: Principal;
}
export interface Message {
    id: string;
    status: Variant_pending_rejected_accepted;
    content: string;
    sender: Principal;
    messageType: Type;
    timestamp: Time;
    bookingRequestId?: string;
    receiver: Principal;
}
export interface CommissionDue {
    status: Variant_pending_paid;
    bookingId: string;
    amount: bigint;
    requesterId: Principal;
}
export interface UserProfile {
    name: string;
    email?: string;
    phoneNumber?: string;
}
export enum Model {
    leadFee = "leadFee",
    none = "none",
    featuredPlacement = "featuredPlacement",
    commission = "commission",
    listingFee = "listingFee"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum Status__1 {
    review = "review",
    active = "active",
    inactive = "inactive"
}
export enum Type {
    offer = "offer",
    message = "message",
    bookingRequest = "bookingRequest"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_paid {
    pending = "pending",
    paid = "paid"
}
export enum Variant_pending_rejected_accepted {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminRevertBan(user: Principal): Promise<void>;
    adminUpdateProfileStatus(profileId: string, status: Status__1): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    canUserAccessMessages(user1: Principal, user2: Principal): Promise<boolean>;
    confirmCommissionPayment(bookingId: string, paid: boolean): Promise<void>;
    createOrUpdateCallerCompanionProfile(profile: Profile, hasPaidFee: boolean): Promise<void>;
    createOrUpdateProfile(profile: Profile): Promise<void>;
    getActiveMonetizationConfig(): Promise<Config>;
    getActiveProfiles(): Promise<Array<Profile>>;
    getAllBookings(): Promise<Array<Request>>;
    getAllProfiles(): Promise<Array<Profile>>;
    getCallerCommissionDues(): Promise<Array<CommissionDue> | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMessagesByParticipants(sender: Principal, receiver: Principal): Promise<Array<Message>>;
    getMessagesByUserId(userId: Principal): Promise<Array<Message>>;
    getPlatformEarnings(): Promise<bigint>;
    getUserBookings(userId: Principal): Promise<Array<Request>>;
    getUserMessageThreads(user: Principal): Promise<Array<MessageThreadInfo>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isBanned(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isCallerBanned(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(message: Message): Promise<void>;
    submitBookingRequest(request: Request): Promise<void>;
    updateBookingRequestStatus(requestId: string, status: Status): Promise<void>;
    updateMonetizationConfig(config: Config): Promise<void>;
}
import type { CommissionDue as _CommissionDue, Config as _Config, Message as _Message, Model as _Model, Profile as _Profile, Rating as _Rating, Request as _Request, Status as _Status, Status__1 as _Status__1, Time as _Time, Type as _Type, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminRevertBan(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRevertBan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRevertBan(arg0);
            return result;
        }
    }
    async adminUpdateProfileStatus(arg0: string, arg1: Status__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProfileStatus(arg0, to_candid_Status__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProfileStatus(arg0, to_candid_Status__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async canUserAccessMessages(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.canUserAccessMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.canUserAccessMessages(arg0, arg1);
            return result;
        }
    }
    async confirmCommissionPayment(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmCommissionPayment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmCommissionPayment(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateCallerCompanionProfile(arg0: Profile, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateCallerCompanionProfile(to_candid_Profile_n5(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateCallerCompanionProfile(to_candid_Profile_n5(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_Profile_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getActiveMonetizationConfig(): Promise<Config> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveMonetizationConfig();
                return from_candid_Config_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveMonetizationConfig();
            return from_candid_Config_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProfiles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProfiles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProfiles(): Promise<Array<Profile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfiles();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfiles();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerCommissionDues(): Promise<Array<CommissionDue> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerCommissionDues();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerCommissionDues();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByParticipants(arg0: Principal, arg1: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByParticipants(arg0, arg1);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByParticipants(arg0, arg1);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByUserId(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByUserId(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByUserId(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformEarnings(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformEarnings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformEarnings();
            return result;
        }
    }
    async getUserBookings(arg0: Principal): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMessageThreads(arg0: Principal): Promise<Array<MessageThreadInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMessageThreads(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMessageThreads(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isBanned(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBanned(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerBanned(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerBanned();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerBanned();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(to_candid_Message_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(to_candid_Message_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitBookingRequest(arg0: Request): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBookingRequest(to_candid_Request_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBookingRequest(to_candid_Request_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingRequestStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingRequestStatus(arg0, to_candid_Status_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingRequestStatus(arg0, to_candid_Status_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMonetizationConfig(arg0: Config): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonetizationConfig(to_candid_Config_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonetizationConfig(to_candid_Config_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CommissionDue_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommissionDue): CommissionDue {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Config_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Config): Config {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Model_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Model): Model {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Request_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Request): Request {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_CommissionDue>]): Array<CommissionDue> | null {
    return value.length === 0 ? null : from_candid_vec_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status__1;
    principal: Principal;
    displayName: string;
    city: string;
    languages: Array<string>;
    ratings: _Rating;
    description: string;
    photoUrl: string;
    priceRange: {
        max: bigint;
        min: bigint;
    };
    category: string;
}): {
    id: string;
    status: Status__1;
    principal: Principal;
    displayName: string;
    city: string;
    languages: Array<string>;
    ratings: Rating;
    description: string;
    photoUrl: string;
    priceRange: {
        max: bigint;
        min: bigint;
    };
    category: string;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n15(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        displayName: value.displayName,
        city: value.city,
        languages: value.languages,
        ratings: value.ratings,
        description: value.description,
        photoUrl: value.photoUrl,
        priceRange: value.priceRange,
        category: value.category
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    scheduledTime: [] | [_Time];
    companionId: string;
    notes: string;
    requestTime: _Time;
    requesterId: Principal;
}): {
    id: string;
    status: Status;
    scheduledTime?: Time;
    companionId: string;
    notes: string;
    requestTime: Time;
    requesterId: Principal;
} {
    return {
        id: value.id,
        status: from_candid_Status_n20(_uploadFile, _downloadFile, value.status),
        scheduledTime: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.scheduledTime)),
        companionId: value.companionId,
        notes: value.notes,
        requestTime: value.requestTime,
        requesterId: value.requesterId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        paid: null;
    };
    bookingId: string;
    amount: bigint;
    requesterId: Principal;
}): {
    status: Variant_pending_paid;
    bookingId: string;
    amount: bigint;
    requesterId: Principal;
} {
    return {
        status: from_candid_variant_n27(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        amount: value.amount,
        requesterId: value.requesterId
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
    phoneNumber: [] | [string];
}): {
    name: string;
    email?: string;
    phoneNumber?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.email)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.phoneNumber))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    content: string;
    sender: Principal;
    messageType: _Type;
    timestamp: _Time;
    bookingRequestId: [] | [string];
    receiver: Principal;
}): {
    id: string;
    status: Variant_pending_rejected_accepted;
    content: string;
    sender: Principal;
    messageType: Type;
    timestamp: Time;
    bookingRequestId?: string;
    receiver: Principal;
} {
    return {
        id: value.id,
        status: from_candid_variant_n37(_uploadFile, _downloadFile, value.status),
        content: value.content,
        sender: value.sender,
        messageType: from_candid_Type_n38(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp,
        bookingRequestId: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.bookingRequestId)),
        receiver: value.receiver
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadFee: [] | [bigint];
    model: _Model;
    featuredPlacementFee: [] | [bigint];
    commissionRate: [] | [bigint];
    listingFee: [] | [bigint];
}): {
    leadFee?: bigint;
    model: Model;
    featuredPlacementFee?: bigint;
    commissionRate?: bigint;
    listingFee?: bigint;
} {
    return {
        leadFee: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.leadFee)),
        model: from_candid_Model_n10(_uploadFile, _downloadFile, value.model),
        featuredPlacementFee: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.featuredPlacementFee)),
        commissionRate: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.commissionRate)),
        listingFee: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.listingFee))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadFee: null;
} | {
    none: null;
} | {
    featuredPlacement: null;
} | {
    commission: null;
} | {
    listingFee: null;
}): Model {
    return "leadFee" in value ? Model.leadFee : "none" in value ? Model.none : "featuredPlacement" in value ? Model.featuredPlacement : "commission" in value ? Model.commission : "listingFee" in value ? Model.listingFee : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    review: null;
} | {
    active: null;
} | {
    inactive: null;
}): Status__1 {
    return "review" in value ? Status__1.review : "active" in value ? Status__1.active : "inactive" in value ? Status__1.inactive : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "rejected" in value ? Status.rejected : "accepted" in value ? Status.accepted : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): Variant_pending_paid {
    return "pending" in value ? Variant_pending_paid.pending : "paid" in value ? Variant_pending_paid.paid : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): Variant_pending_rejected_accepted {
    return "pending" in value ? Variant_pending_rejected_accepted.pending : "rejected" in value ? Variant_pending_rejected_accepted.rejected : "accepted" in value ? Variant_pending_rejected_accepted.accepted : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offer: null;
} | {
    message: null;
} | {
    bookingRequest: null;
}): Type {
    return "offer" in value ? Type.offer : "message" in value ? Type.message : "bookingRequest" in value ? Type.bookingRequest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Profile>): Array<Profile> {
    return value.map((x)=>from_candid_Profile_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Request>): Array<Request> {
    return value.map((x)=>from_candid_Request_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommissionDue>): Array<CommissionDue> {
    return value.map((x)=>from_candid_CommissionDue_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n35(_uploadFile, _downloadFile, x));
}
function to_candid_Config_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Config): _Config {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Message_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Message): _Message {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_Model_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): _Model {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Request_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Request): _Request {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
    phoneNumber?: string;
}): {
    name: string;
    email: [] | [string];
    phoneNumber: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Variant_pending_rejected_accepted;
    content: string;
    sender: Principal;
    messageType: Type;
    timestamp: Time;
    bookingRequestId?: string;
    receiver: Principal;
}): {
    id: string;
    status: {
        pending: null;
    } | {
        rejected: null;
    } | {
        accepted: null;
    };
    content: string;
    sender: Principal;
    messageType: _Type;
    timestamp: _Time;
    bookingRequestId: [] | [string];
    receiver: Principal;
} {
    return {
        id: value.id,
        status: to_candid_variant_n44(_uploadFile, _downloadFile, value.status),
        content: value.content,
        sender: value.sender,
        messageType: to_candid_Type_n45(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp,
        bookingRequestId: value.bookingRequestId ? candid_some(value.bookingRequestId) : candid_none(),
        receiver: value.receiver
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    scheduledTime?: Time;
    companionId: string;
    notes: string;
    requestTime: Time;
    requesterId: Principal;
}): {
    id: string;
    status: _Status;
    scheduledTime: [] | [_Time];
    companionId: string;
    notes: string;
    requestTime: _Time;
    requesterId: Principal;
} {
    return {
        id: value.id,
        status: to_candid_Status_n49(_uploadFile, _downloadFile, value.status),
        scheduledTime: value.scheduledTime ? candid_some(value.scheduledTime) : candid_none(),
        companionId: value.companionId,
        notes: value.notes,
        requestTime: value.requestTime,
        requesterId: value.requesterId
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leadFee?: bigint;
    model: Model;
    featuredPlacementFee?: bigint;
    commissionRate?: bigint;
    listingFee?: bigint;
}): {
    leadFee: [] | [bigint];
    model: _Model;
    featuredPlacementFee: [] | [bigint];
    commissionRate: [] | [bigint];
    listingFee: [] | [bigint];
} {
    return {
        leadFee: value.leadFee ? candid_some(value.leadFee) : candid_none(),
        model: to_candid_Model_n53(_uploadFile, _downloadFile, value.model),
        featuredPlacementFee: value.featuredPlacementFee ? candid_some(value.featuredPlacementFee) : candid_none(),
        commissionRate: value.commissionRate ? candid_some(value.commissionRate) : candid_none(),
        listingFee: value.listingFee ? candid_some(value.listingFee) : candid_none()
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status__1;
    principal: Principal;
    displayName: string;
    city: string;
    languages: Array<string>;
    ratings: Rating;
    description: string;
    photoUrl: string;
    priceRange: {
        max: bigint;
        min: bigint;
    };
    category: string;
}): {
    id: string;
    status: _Status__1;
    principal: Principal;
    displayName: string;
    city: string;
    languages: Array<string>;
    ratings: _Rating;
    description: string;
    photoUrl: string;
    priceRange: {
        max: bigint;
        min: bigint;
    };
    category: string;
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n1(_uploadFile, _downloadFile, value.status),
        principal: value.principal,
        displayName: value.displayName,
        city: value.city,
        languages: value.languages,
        ratings: value.ratings,
        description: value.description,
        photoUrl: value.photoUrl,
        priceRange: value.priceRange,
        category: value.category
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    review: null;
} | {
    active: null;
} | {
    inactive: null;
} {
    return value == Status__1.review ? {
        review: null
    } : value == Status__1.active ? {
        active: null
    } : value == Status__1.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_rejected_accepted): {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == Variant_pending_rejected_accepted.pending ? {
        pending: null
    } : value == Variant_pending_rejected_accepted.rejected ? {
        rejected: null
    } : value == Variant_pending_rejected_accepted.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    offer: null;
} | {
    message: null;
} | {
    bookingRequest: null;
} {
    return value == Type.offer ? {
        offer: null
    } : value == Type.message ? {
        message: null
    } : value == Type.bookingRequest ? {
        bookingRequest: null
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.rejected ? {
        rejected: null
    } : value == Status.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Model): {
    leadFee: null;
} | {
    none: null;
} | {
    featuredPlacement: null;
} | {
    commission: null;
} | {
    listingFee: null;
} {
    return value == Model.leadFee ? {
        leadFee: null
    } : value == Model.none ? {
        none: null
    } : value == Model.featuredPlacement ? {
        featuredPlacement: null
    } : value == Model.commission ? {
        commission: null
    } : value == Model.listingFee ? {
        listingFee: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
